# Generated by Django 4.1.6 on 2023-09-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phoneNumber",
            field=models.CharField(max_length=100),
        ),
    ]
