# Generated by Django 4.1.6 on 2023-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_users_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="role",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
