# Generated by Django 4.1.6 on 2023-09-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_users_issuperviser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="studentNumber",
            field=models.CharField(max_length=100),
        ),
    ]
