# Generated by Django 4.1.6 on 2023-09-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_food_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="id",
        ),
        migrations.AlterField(
            model_name="food",
            name="name",
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
