# Generated by Django 4.1.6 on 2023-09-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_food_id_alter_food_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="food",
        ),
        migrations.DeleteModel(
            name="Food",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
