# Generated by Django 4.1.6 on 2023-09-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_order_food_delete_food_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                ("tableNumber", models.IntegerField()),
                ("receptionTime", models.DateTimeField(auto_now_add=True)),
                ("servedTime", models.DateTimeField(auto_now=True)),
                ("isService", models.IntegerField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.food"
                    ),
                ),
            ],
        ),
    ]
