# Generated by Django 4.1.6 on 2023-09-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_order_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="servedTime",
            field=models.DateTimeField(null=True),
        ),
    ]
