# Generated by Django 4.1.6 on 2023-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_order_servedtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="receptionTime",
            field=models.DateTimeField(null=True),
        ),
    ]
