# Generated by Django 4.1.6 on 2023-09-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_order_receptiontime"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="isCooked",
            field=models.IntegerField(null=True),
        ),
    ]
