# Generated by Django 4.1.6 on 2023-09-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_order_iscooked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="isCooked",
        ),
    ]
