# Generated by Django 4.1.6 on 2023-09-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_eachorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eachorder",
            name="cooker",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.users"
            ),
        ),
        migrations.AlterField(
            model_name="eachorder",
            name="isCooked",
            field=models.IntegerField(default=0),
        ),
    ]
