# Generated by Django 3.2.19 on 2023-09-20 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_eachorder_cooker_alter_eachorder_iscooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='eachorder',
            name='delivery_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_user', to='app.users'),
        ),
        migrations.AddField(
            model_name='eachorder',
            name='is_delivery_call',
            field=models.IntegerField(default=0),
        ),
    ]
